apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-db-pvc
  labels:
    type: local
spec:
  volumeName: app-db-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
