version: '3'

services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library
    volumes:
      - mysql-data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 15s
      timeout: 5s
      retries: 5

  app:
    image: stinkytroll/library-app:v1
    depends_on:
      database:
       condition: service_healthy
    ports:
      - "80:5000"
    environment:
      DB_HOST: "jdbc:mysql://database:3306/library"
      DB_USER: "root"
      DB_PASS: "password"

volumes:
  mysql-data:

  